# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.7"
